
#################################################
# Global test configuration
#################################################
config:

  # Define the metrics we are measuring
  metrics:
    - name: httpRequestTime
      uuid: d7071b36bb804a3c8df69c2de28ac222
      desc: The time from the HTTP request till the completion of the HTTP response
      summarize: [mean_err]
      units: sec

#################################################
# Tracker configuration
#################################################
trackers:

  # Track httpRequestTime as the duration between an `HTTPRequestStartEvent`
  # and an HTTPResponseStartEvent
  - class: tracker.DurationTracker
    metric: httpRequestTime
    events:
      start: HTTPRequestStartEvent
      end: HTTPResponseStartEvent
